[project]
name = "hikari-risa"
version = "0.1.0"
description = "A stateless component manager for hikari."
readme = "README.md"
authors = [
    { name = "Christopher", email = "github.android206@passmail.net" }
]
requires-python = ">=3.10"
dependencies = [
    "hikari>=2.3.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/risa"]

[dependency-groups]
nox = [
    "nox[uv]>=2025.5.1",
]

