line-length = 120
target-version = "py310"

[format]
docstring-code-format = true
docstring-code-line-length = 80
quote-style = "double"
line-ending = "lf"

[lint]
preview = true
select = ["ALL"]

[lint.per-file-ignores]
"noxfile.py" = [
    "D", "DOC" # docstrings
]
"**/__init__.py" = [
    "F401", # imported but unused
    "F403", # unable to detect undefined names
]

[lint.isort]
required-imports = ["from __future__ import annotations"]
force-single-line = true

[lint.pydocstyle]
convention = "numpy"
